num_gpus: 2
max_num_seqs: 256
overload_threshold: 2
gpu_memory_utilization: 0.40
#model: /home/gsw/.cache/huggingface/hub/models--meta-llama--Llama-2-7b-chat-hf/snapshots/f5db02db724555f92da89c216ac04704f23d4590
models:
  -
    name: llm-0
    model: meta-llama/Meta-Llama-3-8B
    tensor_parallel_size: 2
    pipeline_parallel_size: 1
    placement:
      - [0,1]
    mps_percentage: [100, 40]
    model_dtype: bfloat16
  -
    name: llm-1
    model: meta-llama/Meta-Llama-3-8B
    tensor_parallel_size: 2
    pipeline_parallel_size: 1
    placement:
      - [0, 1]
    mps_percentage: [100, 40]
    model_dtype: bfloat16
  # -
  #   name: llm-2
  #   model: /mnt/afs/share/LLMCKPTs/huggyllama/llama-30b
  #   tensor_parallel_size: 4
  #   pipeline_parallel_size: 1
  #   placement:
  #     - [0, 1, 2, 3]
  #   mps_percentage: [100, 40]
  #   model_dtype: fp16
workloads:
  # leave empty, workload generation refer to README
  workload_file:
